name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us investigate.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Scanner (core scanning functionality)
        - Agents (multi-agent AI analysis)
        - Output Formats (JSON, HTML, SARIF, CSV)
        - Graph Visualization (Neo4j)
        - Obfuscation Engine
        - Tests
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: cloud_provider
    attributes:
      label: Cloud Provider
      description: Which cloud provider is this bug related to?
      options:
        - AWS
        - Azure
        - GCP
        - Multi-cloud
        - Not Applicable
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this bug?
      options:
        - Critical (system crash, data loss)
        - High (major functionality broken)
        - Medium (feature partially broken)
        - Low (minor issue, workaround exists)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With configuration '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      placeholder: |
        Paste error logs here...
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      value: |
        - OS: [e.g., macOS 14, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.11.3]
        - Scanner version: [e.g., 2.0]
        - Cloud provider SDK version: [if applicable]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant portions of your config.yaml (redact sensitive data)
      placeholder: |
        Paste relevant config here...
      render: yaml

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, etc.)
